# Generated by Django 5.2.17 on 2026-09-08 04:20

from django.db import migrations, models


def validate_payment_ids(apps, schema_editor):
    Order = apps.get_model('shop', 'Order')
    Order.objects.filter(payment_intent_id='').update(payment_intent_id=None)
    duplicates = Order.objects.exclude(payment_intent_id=None).values('payment_intent_id').annotate(n=models.Count('id')).filter(n__gt=1)
    if duplicates.exists():
        raise RuntimeError('Duplicate Stripe payment IDs exist. Reconcile those orders before migrating; no orders have been deleted.')


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_customer_guest_email_order_guest_email_and_more"),
    ]

    operations = [
        migrations.RunPython(validate_payment_ids, migrations.RunPython.noop),
        migrations.AddField(
            model_name="order",
            name="checkout_session_key",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_intent_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
